name: Run test cases

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.
      - name: Run install and test
        run: |
          npm install
          npx cypress run
